/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'content-types': ContentType;
    categories: Category;
    tags: Tag;
    authors: Author;
    posts: Post;
    pages: Page;
    subscribers: Subscriber;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'content-types': ContentTypesSelect<false> | ContentTypesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-types".
 */
export interface ContentType {
  id: string;
  label: string;
  /**
   * Stable value used internally by frontend filters and post routing.
   */
  key: string;
  /**
   * Public route base such as /insights, /whitepapers, or /webinars.
   */
  routeBase: string;
  active?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  /**
   * Auto-generated from the category name when left empty.
   */
  slug: string;
  description?: string | null;
  featured?: boolean | null;
  /**
   * Hex value such as #0F172A
   */
  color?: string | null;
  image?: (string | null) | Media;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    metaImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    metaImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: string;
  name: string;
  slug: string;
  role?: string | null;
  bio?: string | null;
  avatar?: (string | null) | Media;
  email?: string | null;
  linkedUser?: (string | null) | User;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    metaImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  /**
   * Public headline shown in cards, SEO, and the post detail page.
   */
  title: string;
  /**
   * Estimated reading time in minutes.
   */
  readingTime?: number | null;
  /**
   * Shareable URL segment. Auto-generated from title and adjusted if a duplicate already exists.
   */
  slug: string;
  /**
   * Controls the public section and route. Seeded options are Insight, White Paper, and Webinar.
   */
  contentType: string | ContentType;
  /**
   * Draft stays hidden from the public site. Published is visible on the frontend. Archived is stored but excluded from public queries.
   */
  status: 'draft' | 'published' | 'archived';
  type?: string | null;
  authors: (string | Author)[];
  /**
   * Main taxonomy used in UI filters like Finance, Marketing, and Technology.
   */
  primaryCategory: string | Category;
  /**
   * Short summary used on listing pages and hero cards.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Main card and detail-page image.
   */
  featuredImage: string | Media;
  /**
   * Optional downloadable asset for whitepaper entries.
   */
  downloadAsset?: (string | null) | Media;
  gallery?:
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional event stream, replay, or registration video URL for webinar pages.
   */
  videoUrl?: string | null;
  /**
   * Optional canonical, download, or registration URL.
   */
  externalUrl?: string | null;
  featured?: boolean | null;
  pinned?: boolean | null;
  /**
   * Required for published content. Defaults to now when you publish.
   */
  publishedAt?: string | null;
  /**
   * Controls the gated white paper form, delivery mode, and post-submit behavior.
   */
  leadCapture?: {
    enabled?: boolean | null;
    openDeliveryInNewTab?: boolean | null;
    deliveryMode?: ('download' | 'read' | 'redirect') | null;
    formTitle?: string | null;
    submitLabel?: string | null;
    formDescription?: string | null;
    successMessage?: string | null;
    newsletterLabel?: string | null;
    consentLabel?: string | null;
    /**
     * Optional override destination after form submission. If empty, the white paper external URL or uploaded file is used.
     */
    deliveryUrl?: string | null;
  };
  tags?: (string | Tag)[] | null;
  /**
   * Optional related content suggestions shown near this post.
   */
  relatedPosts?: (string | Post)[] | null;
  cta: {
    primary: {
      label: string;
      type: 'custom' | 'page' | 'post' | 'category';
      /**
       * Examples: /contact, https://example.com
       */
      url?: string | null;
      page?: (string | null) | Page;
      post?: (string | null) | Post;
      category?: (string | null) | Category;
      newTab?: boolean | null;
    };
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    metaImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  createdBy?: (string | null) | User;
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  template: 'standard' | 'landing' | 'contact' | 'support' | 'legal';
  hero: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
    primaryAction: {
      label: string;
      type: 'custom' | 'page' | 'post' | 'category';
      /**
       * Examples: /contact, https://example.com
       */
      url?: string | null;
      page?: (string | null) | Page;
      post?: (string | null) | Post;
      category?: (string | null) | Category;
      newTab?: boolean | null;
    };
    secondaryAction: {
      label: string;
      type: 'custom' | 'page' | 'post' | 'category';
      /**
       * Examples: /contact, https://example.com
       */
      url?: string | null;
      page?: (string | null) | Page;
      post?: (string | null) | Post;
      category?: (string | null) | Category;
      newTab?: boolean | null;
    };
  };
  summary?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredPosts?: (string | Post)[] | null;
  hideFromNavigation?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    metaImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: string;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  status: 'subscribed' | 'unsubscribed';
  source?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  resourceType: 'whitepaper';
  post: string | Post;
  name: string;
  email: string;
  jobTitle?: string | null;
  company?: string | null;
  country?: string | null;
  newsletterOptIn?: boolean | null;
  consentAccepted: boolean;
  deliveryMode: 'read' | 'download' | 'redirect';
  submittedAt: string;
  deliveryTarget?: string | null;
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'content-types';
        value: string | ContentType;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: string | Author;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: string | Subscriber;
      } | null)
    | ({
        relationTo: 'leads';
        value: string | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-types_select".
 */
export interface ContentTypesSelect<T extends boolean = true> {
  label?: T;
  key?: T;
  routeBase?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  featured?: T;
  color?: T;
  image?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        metaImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        metaImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  email?: T;
  linkedUser?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        metaImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  readingTime?: T;
  slug?: T;
  contentType?: T;
  status?: T;
  type?: T;
  authors?: T;
  primaryCategory?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  downloadAsset?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  videoUrl?: T;
  externalUrl?: T;
  featured?: T;
  pinned?: T;
  publishedAt?: T;
  leadCapture?:
    | T
    | {
        enabled?: T;
        openDeliveryInNewTab?: T;
        deliveryMode?: T;
        formTitle?: T;
        submitLabel?: T;
        formDescription?: T;
        successMessage?: T;
        newsletterLabel?: T;
        consentLabel?: T;
        deliveryUrl?: T;
      };
  tags?: T;
  relatedPosts?: T;
  cta?:
    | T
    | {
        primary?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              post?: T;
              category?: T;
              newTab?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        metaImage?: T;
        noIndex?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  template?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
        image?: T;
        primaryAction?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              post?: T;
              category?: T;
              newTab?: T;
            };
        secondaryAction?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              post?: T;
              category?: T;
              newTab?: T;
            };
      };
  summary?: T;
  content?: T;
  featuredPosts?: T;
  hideFromNavigation?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        metaImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  lastName?: T;
  status?: T;
  source?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  resourceType?: T;
  post?: T;
  name?: T;
  email?: T;
  jobTitle?: T;
  company?: T;
  country?: T;
  newsletterOptIn?: T;
  consentAccepted?: T;
  deliveryMode?: T;
  submittedAt?: T;
  deliveryTarget?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  siteTagline?: string | null;
  siteDescription?: string | null;
  logo?: (string | null) | Media;
  favicon?: (string | null) | Media;
  defaultShareImage?: (string | null) | Media;
  contactEmail?: string | null;
  /**
   * Admin recipients for white paper lead notifications. EmailJS credentials are read from environment variables.
   */
  leadNotificationEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  headerLinks?:
    | {
        item: {
          label: string;
          type: 'custom' | 'page' | 'post' | 'category';
          /**
           * Examples: /contact, https://example.com
           */
          url?: string | null;
          page?: (string | null) | Page;
          post?: (string | null) | Post;
          category?: (string | null) | Category;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  footerSections?:
    | {
        title: string;
        links?:
          | {
              item: {
                label: string;
                type: 'custom' | 'page' | 'post' | 'category';
                /**
                 * Examples: /contact, https://example.com
                 */
                url?: string | null;
                page?: (string | null) | Page;
                post?: (string | null) | Post;
                category?: (string | null) | Category;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    enabled?: boolean | null;
    title?: string | null;
    description?: string | null;
    submitLabel?: string | null;
  };
  /**
   * Reference-only labels for environment-based integrations used by the frontend and API routes.
   */
  systemIntegrations?: {
    emailProvider?: string | null;
    emailCredentialNote?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    metaImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteTagline?: T;
  siteDescription?: T;
  logo?: T;
  favicon?: T;
  defaultShareImage?: T;
  contactEmail?: T;
  leadNotificationEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  headerLinks?:
    | T
    | {
        item?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              post?: T;
              category?: T;
              newTab?: T;
            };
        id?: T;
      };
  footerSections?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              item?:
                | T
                | {
                    label?: T;
                    type?: T;
                    url?: T;
                    page?: T;
                    post?: T;
                    category?: T;
                    newTab?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  newsletter?:
    | T
    | {
        enabled?: T;
        title?: T;
        description?: T;
        submitLabel?: T;
      };
  systemIntegrations?:
    | T
    | {
        emailProvider?: T;
        emailCredentialNote?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        metaImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}